sudo: false

addons:
  apt:
    packages:
      - zsh

install:
  - ./setup.zsh
  - ./lib/nMoonLib/.run luarocks remove moonscript
  - ./lib/nMoonLib/.run luarocks install moonscript

script: true

deploy:
  skip_cleanup: true
